name: flutter_lyric
description: This plugin is a music lyric reader,support translation lyrics,smooth animation,custom UI,Parse.;
version: 2.0.1+5
homepage: https://github.com/ozyl/flutter_lyric
email: zylvip@163.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter


plugin:
  platforms:
    android:
      package: cn.okzyl.flutter_lyric
      pluginClass: FlutterLyricPlugin
    ios:
      pluginClass: FlutterLyricPlugin
    web:
      pluginClass: LyricsReaderWeb
      fileName: lyrics_reader_web.dart
    macos:
      pluginClass: FlutterLyricPlugin
    linux:
      pluginClass: FlutterLyricPlugin
    windows:
      pluginClass: FlutterLyricPlugin